
services:
  redis:
    image: redis:7.2.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persists data between container restarts
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s

volumes:
  redis_data: