spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/side_droppii
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
# Application-specific settings
application:
  security:
    jwt:
      secret-key: "your_jwt_secret_key_here_make_it_at_least_32_characters_long"
      token-validity-in-seconds: 3600
      refresh-token-validity-in-seconds: 2592000

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /
